//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EUCases.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EUCases.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AddNewLink {
            get {
                object obj = ResourceManager.GetObject("AddNewLink", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CheckForLinks {
            get {
                object obj = ResourceManager.GetObject("CheckForLinks", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Credentials {
            get {
                object obj = ResourceManager.GetObject("Settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RemoveAllLinks {
            get {
                object obj = ResourceManager.GetObject("RemoveAllLinks", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RemoveLink {
            get {
                object obj = ResourceManager.GetObject("RemoveLink", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SaveXml {
            get {
                object obj = ResourceManager.GetObject("SaveXml", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var EUCASES_LANGS_NUMS = [];
        ///EUCASES_LANGS_NUMS[1] = &apos;bg&apos;;
        ///EUCASES_LANGS_NUMS[2] = &apos;de&apos;;
        ///EUCASES_LANGS_NUMS[3] = &apos;fr&apos;;
        ///EUCASES_LANGS_NUMS[4] = &apos;en&apos;;
        ///EUCASES_LANGS_NUMS[5] = &apos;it&apos;;
        ///EUCASES_LANGS_NUMS[&apos;bg&apos;] = 1;
        ///EUCASES_LANGS_NUMS[&apos;de&apos;] = 2;
        ///EUCASES_LANGS_NUMS[&apos;fr&apos;] = 3;
        ///EUCASES_LANGS_NUMS[&apos;en&apos;] = 4;
        ///EUCASES_LANGS_NUMS[&apos;it&apos;] = 5;
        ///
        ///var EUCASES_LANGS_WIN = [];
        ///EUCASES_LANGS_WIN[&apos;bg&apos;] = 1026;
        ///EUCASES_LANGS_WIN[&apos;de&apos;] = 1031;
        ///EUCASES_LANGS_WIN[&apos;fr&apos;] = 1036;
        ///EUCASES_LANGS_WIN[&apos;en&apos;] = 2057;
        ///EUCASES_L [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Script {
            get {
                return ResourceManager.GetString("Script", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Settings {
            get {
                object obj = ResourceManager.GetObject("Settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #eucasesTempContextMenu, #eucasesTempConceptContextMenu {
        ///    cursor: pointer;
        ///    list-style-type: none;
        ///    background-color: #f0f0f0;
        ///    float: left;
        ///    position: absolute;
        ///    border: 1px solid #979797;
        ///    font-size: 14px !important;
        ///    line-height: 14px !important;
        ///    font-family: Calibri;
        ///}
        ///
        ///    #eucasesTempContextMenu li, #eucasesTempConceptContextMenu li {
        ///        border-left: 1px solid #d7d7d7;
        ///        border-bottom: 1px solid #d7d7d7;
        ///        padding: 3px;
        ///        font-size: 1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Style {
            get {
                return ResourceManager.GetString("Style", resourceCulture);
            }
        }
    }
}
