//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EUCases.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TranslationFR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TranslationFR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EUCases.Resource.TranslationFR", typeof(TranslationFR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tous.
        /// </summary>
        internal static string cAll {
            get {
                return ResourceManager.GetString("cAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler.
        /// </summary>
        internal static string cCancel {
            get {
                return ResourceManager.GetString("cCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez sélectionner le texte pour insérer un lien..
        /// </summary>
        internal static string cCannotAddLink {
            get {
                return ResourceManager.GetString("cCannotAddLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vérifier les liens.
        /// </summary>
        internal static string cCheckFrLinks {
            get {
                return ResourceManager.GetString("cCheckFrLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string cConfirmation {
            get {
                return ResourceManager.GetString("cConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EULinksChecker.
        /// </summary>
        internal static string cEULinksChecker {
            get {
                return ResourceManager.GetString("cEULinksChecker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informations.
        /// </summary>
        internal static string cInformation {
            get {
                return ResourceManager.GetString("cInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insérer le lien.
        /// </summary>
        internal static string cInsertLink {
            get {
                return ResourceManager.GetString("cInsertLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Langue de l’interface:.
        /// </summary>
        internal static string cLang {
            get {
                return ResourceManager.GetString("cLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lien vers.
        /// </summary>
        internal static string cLinkTo {
            get {
                return ResourceManager.GetString("cLinkTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tous les documents.
        /// </summary>
        internal static string cm_AllDocuments {
            get {
                return ResourceManager.GetString("cm_AllDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paramètres.
        /// </summary>
        internal static string cm_Credentials {
            get {
                return ResourceManager.GetString("cm_Credentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents indexés avec ce terme:.
        /// </summary>
        internal static string cm_DocumentsIndexedWithThisTerm {
            get {
                return ResourceManager.GetString("cm_DocumentsIndexedWithThisTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents faisant référence à cet acte / disposition:.
        /// </summary>
        internal static string cm_DocumentsReferringToThisAct {
            get {
                return ResourceManager.GetString("cm_DocumentsReferringToThisAct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jurisprudence de l&apos;UE.
        /// </summary>
        internal static string cm_EuCL {
            get {
                return ResourceManager.GetString("cm_EuCL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Législation de l&apos;UE.
        /// </summary>
        internal static string cm_EuL {
            get {
                return ResourceManager.GetString("cm_EuL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insérer un lien.
        /// </summary>
        internal static string cm_InsertLink {
            get {
                return ResourceManager.GetString("cm_InsertLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jurisprudence nationale.
        /// </summary>
        internal static string cm_NaCL {
            get {
                return ResourceManager.GetString("cm_NaCL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Législation nationale.
        /// </summary>
        internal static string cm_NaL {
            get {
                return ResourceManager.GetString("cm_NaL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer le lien.
        /// </summary>
        internal static string cm_RemoveLink {
            get {
                return ResourceManager.GetString("cm_RemoveLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher info-bulle.
        /// </summary>
        internal static string cm_ShowToolTip {
            get {
                return ResourceManager.GetString("cm_ShowToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous êtes sur le point de changer la langue de l&apos;interface utilisateur..
        /// </summary>
        internal static string cMsgChgLng {
            get {
                return ResourceManager.GetString("cMsgChgLng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucun lien établi par EULinksChecker..
        /// </summary>
        internal static string cMsgNoLinksSetByELCFound {
            get {
                return ResourceManager.GetString("cMsgNoLinksSetByELCFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string cOK {
            get {
                return ResourceManager.GetString("cOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opérations.
        /// </summary>
        internal static string cOperations {
            get {
                return ResourceManager.GetString("cOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe.
        /// </summary>
        internal static string cPassword {
            get {
                return ResourceManager.GetString("cPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez sélectionner le texte avec des liens établis par EULinksChecker..
        /// </summary>
        internal static string cPlsSelLink {
            get {
                return ResourceManager.GetString("cPlsSelLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EULinksChecker vérifiera s’il existe des références menant vers la législation et la jurisprudence de l&apos;Union européenne et mettra des liens vers les dispositions cités. Cela peut prendre un certain temps.Veuillez  confirmer!.
        /// </summary>
        internal static string cPlzConfirm {
            get {
                return ResourceManager.GetString("cPlzConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez confirmer la suppression des liens établis par EULinksChecker..
        /// </summary>
        internal static string cPlzConfirmRmLnk {
            get {
                return ResourceManager.GetString("cPlzConfirmRmLnk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les liens établis par EULinksChecker seront supprimés. Veuillez confirmer!.
        /// </summary>
        internal static string cPlzConfirmRmLnkSel {
            get {
                return ResourceManager.GetString("cPlzConfirmRmLnkSel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez entrez l&apos;URL complète.
        /// </summary>
        internal static string cPlzEnterCompleteUrl {
            get {
                return ResourceManager.GetString("cPlzEnterCompleteUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer les liens.
        /// </summary>
        internal static string cRemoveLinks {
            get {
                return ResourceManager.GetString("cRemoveLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer les liens de la sélection.
        /// </summary>
        internal static string cRemoveLinksFromSelection {
            get {
                return ResourceManager.GetString("cRemoveLinksFromSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insérez manuellement un lien vers une ressource Web externe.
        /// </summary>
        internal static string cStAddNewLink {
            get {
                return ResourceManager.GetString("cStAddNewLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paramètres.
        /// </summary>
        internal static string cStCredentials {
            get {
                return ResourceManager.GetString("cStCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identification et le marquage des références vers la législation et la jurisprudence de l&apos;Union européenne.
        /// </summary>
        internal static string cStPutLinksAndTerms {
            get {
                return ResourceManager.GetString("cStPutLinksAndTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrait de liens menant vers la législation et la jurisprudence de l&apos;UE établis par EULinksChecker à partir du texte sélectionné.
        /// </summary>
        internal static string cStRemove1 {
            get {
                return ResourceManager.GetString("cStRemove1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrait de liens menant vers la législation et la jurisprudence de l&apos;UE établis par EULinksChecker avec la fonction  &quot;Vérifier les liens&quot;.
        /// </summary>
        internal static string cStRemoveLinksAndTerms {
            get {
                return ResourceManager.GetString("cStRemoveLinksAndTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enregistrer le texte au format XML.
        /// </summary>
        internal static string cStSave2Xml {
            get {
                return ResourceManager.GetString("cStSave2Xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La vérification des liens est terminée..
        /// </summary>
        internal static string cSuccess {
            get {
                return ResourceManager.GetString("cSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom d&apos;utilisateur.
        /// </summary>
        internal static string cUserName {
            get {
                return ResourceManager.GetString("cUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enregistrer le texte au format XML.
        /// </summary>
        internal static string Save2Xml {
            get {
                return ResourceManager.GetString("Save2Xml", resourceCulture);
            }
        }
    }
}
