//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EUCases.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TranslationDE {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TranslationDE() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EUCases.Resource.TranslationDE", typeof(TranslationDE).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alles.
        /// </summary>
        internal static string cAll {
            get {
                return ResourceManager.GetString("cAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stornieren.
        /// </summary>
        internal static string cCancel {
            get {
                return ResourceManager.GetString("cCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte, markieren Sie einen Text um einen Link einzufügen..
        /// </summary>
        internal static string cCannotAddLink {
            get {
                return ResourceManager.GetString("cCannotAddLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Überprüfung für Links.
        /// </summary>
        internal static string cCheckFrLinks {
            get {
                return ResourceManager.GetString("cCheckFrLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestätigung.
        /// </summary>
        internal static string cConfirmation {
            get {
                return ResourceManager.GetString("cConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EU Links Checker.
        /// </summary>
        internal static string cEULinksChecker {
            get {
                return ResourceManager.GetString("cEULinksChecker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string cInformation {
            get {
                return ResourceManager.GetString("cInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link einfügen.
        /// </summary>
        internal static string cInsertLink {
            get {
                return ResourceManager.GetString("cInsertLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprache der Schnittstelle:.
        /// </summary>
        internal static string cLang {
            get {
                return ResourceManager.GetString("cLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link zu.
        /// </summary>
        internal static string cLinkTo {
            get {
                return ResourceManager.GetString("cLinkTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle Dokumente.
        /// </summary>
        internal static string cm_AllDocuments {
            get {
                return ResourceManager.GetString("cm_AllDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellungen.
        /// </summary>
        internal static string cm_Credentials {
            get {
                return ResourceManager.GetString("cm_Credentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dokumente mit diesem Begriff indiziert:.
        /// </summary>
        internal static string cm_DocumentsIndexedWithThisTerm {
            get {
                return ResourceManager.GetString("cm_DocumentsIndexedWithThisTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dokumente, die auf diesen Akt / Vorschrift verweisen.
        /// </summary>
        internal static string cm_DocumentsReferringToThisAct {
            get {
                return ResourceManager.GetString("cm_DocumentsReferringToThisAct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EU-Rechtsprechung.
        /// </summary>
        internal static string cm_EuCL {
            get {
                return ResourceManager.GetString("cm_EuCL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EU-Gesetzgebung.
        /// </summary>
        internal static string cm_EuL {
            get {
                return ResourceManager.GetString("cm_EuL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link einfügen.
        /// </summary>
        internal static string cm_InsertLink {
            get {
                return ResourceManager.GetString("cm_InsertLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationale Rechtsprechung.
        /// </summary>
        internal static string cm_NaCL {
            get {
                return ResourceManager.GetString("cm_NaCL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationale Gesetzgebung.
        /// </summary>
        internal static string cm_NaL {
            get {
                return ResourceManager.GetString("cm_NaL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link entfernen.
        /// </summary>
        internal static string cm_RemoveLink {
            get {
                return ResourceManager.GetString("cm_RemoveLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hinweis anzeigen.
        /// </summary>
        internal static string cm_ShowToolTip {
            get {
                return ResourceManager.GetString("cm_ShowToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie sind dabei, die Sprache der Benutzeroberfläche zu ändern..
        /// </summary>
        internal static string cMsgChgLng {
            get {
                return ResourceManager.GetString("cMsgChgLng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine Links vom EULinksChecker gefunden..
        /// </summary>
        internal static string cMsgNoLinksSetByELCFound {
            get {
                return ResourceManager.GetString("cMsgNoLinksSetByELCFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestätigen.
        /// </summary>
        internal static string cOK {
            get {
                return ResourceManager.GetString("cOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handhabungen.
        /// </summary>
        internal static string cOperations {
            get {
                return ResourceManager.GetString("cOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kennwort.
        /// </summary>
        internal static string cPassword {
            get {
                return ResourceManager.GetString("cPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte, wählen Sie einen Text mit Links gesetzt vom EULinksChecker..
        /// </summary>
        internal static string cPlsSelLink {
            get {
                return ResourceManager.GetString("cPlsSelLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EULinksChecker wird überprüfen ob Verweise auf EU-Gesetzgebung oder Rechtsprechung  vorhanden sind und wird Links zu den zitierten Rechtsakten einfügen. Dies kann eine Weile dauern. Bitte, bestätigen!.
        /// </summary>
        internal static string cPlzConfirm {
            get {
                return ResourceManager.GetString("cPlzConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte bestätigen Sie die Entfernung von Links gesetzt von EULinksCheker..
        /// </summary>
        internal static string cPlzConfirmRmLnk {
            get {
                return ResourceManager.GetString("cPlzConfirmRmLnk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die vom EULinksChecker gesetzten Links werden gelöscht. Bitte, bestätigen!.
        /// </summary>
        internal static string cPlzConfirmRmLnkSel {
            get {
                return ResourceManager.GetString("cPlzConfirmRmLnkSel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte geben Sie die vollständige URL..
        /// </summary>
        internal static string cPlzEnterCompleteUrl {
            get {
                return ResourceManager.GetString("cPlzEnterCompleteUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links entfernen.
        /// </summary>
        internal static string cRemoveLinks {
            get {
                return ResourceManager.GetString("cRemoveLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links von Auswahl entfernen.
        /// </summary>
        internal static string cRemoveLinksFromSelection {
            get {
                return ResourceManager.GetString("cRemoveLinksFromSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manuelle Einfügung vom Link zur externen Web-Ressource.
        /// </summary>
        internal static string cStAddNewLink {
            get {
                return ResourceManager.GetString("cStAddNewLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellungen.
        /// </summary>
        internal static string cStCredentials {
            get {
                return ResourceManager.GetString("cStCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erkennung und Hervorhebung von Verweisen auf EU-Gesetzgebung und Rechtsprechung.
        /// </summary>
        internal static string cStPutLinksAndTerms {
            get {
                return ResourceManager.GetString("cStPutLinksAndTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entfernung von den vom EULinksChecker gesetzten Links die auf EU-Gesetzgebung und Rechtsprechung verweisen.
        /// </summary>
        internal static string cStRemove1 {
            get {
                return ResourceManager.GetString("cStRemove1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entfernung der Links gesetzt von &apos;&apos;Überprüfen Sie für Links&apos;&apos; Funktion des EULinksCheckers.
        /// </summary>
        internal static string cStRemoveLinksAndTerms {
            get {
                return ResourceManager.GetString("cStRemoveLinksAndTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern Sie den Text in XML-file.
        /// </summary>
        internal static string cStSave2Xml {
            get {
                return ResourceManager.GetString("cStSave2Xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Überprüfung für Links abgeschlossen..
        /// </summary>
        internal static string cSuccess {
            get {
                return ResourceManager.GetString("cSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzername.
        /// </summary>
        internal static string cUserName {
            get {
                return ResourceManager.GetString("cUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text in XML-Datei speichern.
        /// </summary>
        internal static string Save2Xml {
            get {
                return ResourceManager.GetString("Save2Xml", resourceCulture);
            }
        }
    }
}
