//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EUCases.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TranslationBG {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TranslationBG() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EUCases.Resource.TranslationBG", typeof(TranslationBG).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всички.
        /// </summary>
        internal static string cAll {
            get {
                return ResourceManager.GetString("cAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Откажи.
        /// </summary>
        internal static string cCancel {
            get {
                return ResourceManager.GetString("cCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моля, маркирайте текст, за да вмъкнете връзка..
        /// </summary>
        internal static string cCannotAddLink {
            get {
                return ResourceManager.GetString("cCannotAddLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Провери за връзки.
        /// </summary>
        internal static string cCheckFrLinks {
            get {
                return ResourceManager.GetString("cCheckFrLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потвърждение.
        /// </summary>
        internal static string cConfirmation {
            get {
                return ResourceManager.GetString("cConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EULinksChecker.
        /// </summary>
        internal static string cEULinksChecker {
            get {
                return ResourceManager.GetString("cEULinksChecker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация.
        /// </summary>
        internal static string cInformation {
            get {
                return ResourceManager.GetString("cInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Постави връзка.
        /// </summary>
        internal static string cInsertLink {
            get {
                return ResourceManager.GetString("cInsertLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Език на интерфейса:.
        /// </summary>
        internal static string cLang {
            get {
                return ResourceManager.GetString("cLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Свържи с.
        /// </summary>
        internal static string cLinkTo {
            get {
                return ResourceManager.GetString("cLinkTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всички документи.
        /// </summary>
        internal static string cm_AllDocuments {
            get {
                return ResourceManager.GetString("cm_AllDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки.
        /// </summary>
        internal static string cm_Credentials {
            get {
                return ResourceManager.GetString("cm_Credentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Документи, индексирани с този термин:.
        /// </summary>
        internal static string cm_DocumentsIndexedWithThisTerm {
            get {
                return ResourceManager.GetString("cm_DocumentsIndexedWithThisTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Документи, препращащи към този акт / разпоредба:.
        /// </summary>
        internal static string cm_DocumentsReferringToThisAct {
            get {
                return ResourceManager.GetString("cm_DocumentsReferringToThisAct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Съдебна практика на ЕС.
        /// </summary>
        internal static string cm_EuCL {
            get {
                return ResourceManager.GetString("cm_EuCL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Законодателство на ЕС.
        /// </summary>
        internal static string cm_EuL {
            get {
                return ResourceManager.GetString("cm_EuL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Постави връзка.
        /// </summary>
        internal static string cm_InsertLink {
            get {
                return ResourceManager.GetString("cm_InsertLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Национална съдебна практика.
        /// </summary>
        internal static string cm_NaCL {
            get {
                return ResourceManager.GetString("cm_NaCL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Национално законодателство.
        /// </summary>
        internal static string cm_NaL {
            get {
                return ResourceManager.GetString("cm_NaL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изтрий връзката.
        /// </summary>
        internal static string cm_RemoveLink {
            get {
                return ResourceManager.GetString("cm_RemoveLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Покажи подсказка.
        /// </summary>
        internal static string cm_ShowToolTip {
            get {
                return ResourceManager.GetString("cm_ShowToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to С това действие ще промените езика на потребителския интерфейс..
        /// </summary>
        internal static string cMsgChgLng {
            get {
                return ResourceManager.GetString("cMsgChgLng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не са намерени връзки, поставени от EULinksChecker..
        /// </summary>
        internal static string cMsgNoLinksSetByELCFound {
            get {
                return ResourceManager.GetString("cMsgNoLinksSetByELCFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потвърди.
        /// </summary>
        internal static string cOK {
            get {
                return ResourceManager.GetString("cOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Операции.
        /// </summary>
        internal static string cOperations {
            get {
                return ResourceManager.GetString("cOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Парола.
        /// </summary>
        internal static string cPassword {
            get {
                return ResourceManager.GetString("cPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моля, маркирайте текст с връзки, поставени от EULinksChecker..
        /// </summary>
        internal static string cPlsSelLink {
            get {
                return ResourceManager.GetString("cPlsSelLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EULinksChecker ще провери дали съществуват препратки към законодателството и съдебната практика на Европейския съюз и ще постави връзки към цитираните нормативни актове. Това може да отнеме известно време. Моля, потвърдете!.
        /// </summary>
        internal static string cPlzConfirm {
            get {
                return ResourceManager.GetString("cPlzConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моля, потвърдете изтриването на връзките, поставени от EULinksChecker..
        /// </summary>
        internal static string cPlzConfirmRmLnk {
            get {
                return ResourceManager.GetString("cPlzConfirmRmLnk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Връзките, поставени от EULinksChecker ще бъдат изтрити. Моля, потвърдете!.
        /// </summary>
        internal static string cPlzConfirmRmLnkSel {
            get {
                return ResourceManager.GetString("cPlzConfirmRmLnkSel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моля, въведете пълния URL-адрес..
        /// </summary>
        internal static string cPlzEnterCompleteUrl {
            get {
                return ResourceManager.GetString("cPlzEnterCompleteUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Премахни връзките.
        /// </summary>
        internal static string cRemoveLinks {
            get {
                return ResourceManager.GetString("cRemoveLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Премахни връзките от избраното.
        /// </summary>
        internal static string cRemoveLinksFromSelection {
            get {
                return ResourceManager.GetString("cRemoveLinksFromSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ръчно поставяне на връзка към външен уеб ресурс.
        /// </summary>
        internal static string cStAddNewLink {
            get {
                return ResourceManager.GetString("cStAddNewLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки.
        /// </summary>
        internal static string cStCredentials {
            get {
                return ResourceManager.GetString("cStCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разпознаване и маркиране на препратки към законодателството и съдебната практика на Европейския съюз.
        /// </summary>
        internal static string cStPutLinksAndTerms {
            get {
                return ResourceManager.GetString("cStPutLinksAndTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Премахване в маркирания текст на поставените от EULinksChecker връзки към законодателството и съдебната практика на Европейския съюз.
        /// </summary>
        internal static string cStRemove1 {
            get {
                return ResourceManager.GetString("cStRemove1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Премахване на връзките към законодателството и съдебната практика на Европейския съюз, поставени от EULinksChecker с функцията &quot;Провери за връзки&quot;.
        /// </summary>
        internal static string cStRemoveLinksAndTerms {
            get {
                return ResourceManager.GetString("cStRemoveLinksAndTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запиши текста в XML-file.
        /// </summary>
        internal static string cStSave2Xml {
            get {
                return ResourceManager.GetString("cStSave2Xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверката за връзки приключи..
        /// </summary>
        internal static string cSuccess {
            get {
                return ResourceManager.GetString("cSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потребителско име.
        /// </summary>
        internal static string cUserName {
            get {
                return ResourceManager.GetString("cUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запиши текста в XML-file.
        /// </summary>
        internal static string Save2Xml {
            get {
                return ResourceManager.GetString("Save2Xml", resourceCulture);
            }
        }
    }
}
