//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EUCases.EULinksCheckerWordAddIn.ServiceReference
{
    using System.Runtime.Serialization;
    using System;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "AkomaNtosoXmlResult", Namespace = "http://schemas.datacontract.org/2004/07/EUCases.FrontendWcf.Classes")]
    [System.SerializableAttribute()]
    public partial class AkomaNtosoXmlResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {

        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LinksCountField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XmlField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string langField;

        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LinksCount
        {
            get
            {
                return this.LinksCountField;
            }
            set
            {
                if ((this.LinksCountField.Equals(value) != true))
                {
                    this.LinksCountField = value;
                    this.RaisePropertyChanged("LinksCount");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Xml
        {
            get
            {
                return this.XmlField;
            }
            set
            {
                if ((object.ReferenceEquals(this.XmlField, value) != true))
                {
                    this.XmlField = value;
                    this.RaisePropertyChanged("Xml");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lang
        {
            get
            {
                return this.langField;
            }
            set
            {
                if ((object.ReferenceEquals(this.langField, value) != true))
                {
                    this.langField = value;
                    this.RaisePropertyChanged("lang");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "TextPosWrapper", Namespace = "http://schemas.datacontract.org/2004/07/EUCases.Tools.Classes")]
    [System.SerializableAttribute()]
    public partial class TextPosWrapper : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {

        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EUCases.EULinksCheckerWordAddIn.ServiceReference.EurovocTextPos[] AnnotationsTextPosField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EUCases.EULinksCheckerWordAddIn.ServiceReference.LinkTextPos[] LinksTextPosField;

        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public EUCases.EULinksCheckerWordAddIn.ServiceReference.EurovocTextPos[] AnnotationsTextPos
        {
            get
            {
                return this.AnnotationsTextPosField;
            }
            set
            {
                if ((object.ReferenceEquals(this.AnnotationsTextPosField, value) != true))
                {
                    this.AnnotationsTextPosField = value;
                    this.RaisePropertyChanged("AnnotationsTextPos");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public EUCases.EULinksCheckerWordAddIn.ServiceReference.LinkTextPos[] LinksTextPos
        {
            get
            {
                return this.LinksTextPosField;
            }
            set
            {
                if ((object.ReferenceEquals(this.LinksTextPosField, value) != true))
                {
                    this.LinksTextPosField = value;
                    this.RaisePropertyChanged("LinksTextPos");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "EurovocTextPos", Namespace = "http://schemas.datacontract.org/2004/07/EUCases.Tools.Classes")]
    [System.SerializableAttribute()]
    public partial class EurovocTextPos : EUCases.EULinksCheckerWordAddIn.ServiceReference.TextPos
    {

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                if ((object.ReferenceEquals(this.IdField, value) != true))
                {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "LinkTextPos", Namespace = "http://schemas.datacontract.org/2004/07/EUCases.Tools.Classes")]
    [System.SerializableAttribute()]
    public partial class LinkTextPos : EUCases.EULinksCheckerWordAddIn.ServiceReference.TextPos
    {

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CelexField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferrenceInfoField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Celex
        {
            get
            {
                return this.CelexField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CelexField, value) != true))
                {
                    this.CelexField = value;
                    this.RaisePropertyChanged("Celex");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReferrenceInfo
        {
            get
            {
                return this.ReferrenceInfoField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ReferrenceInfoField, value) != true))
                {
                    this.ReferrenceInfoField = value;
                    this.RaisePropertyChanged("ReferrenceInfo");
                }
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "TextPos", Namespace = "http://schemas.datacontract.org/2004/07/EUCases.Tools.Classes")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EUCases.EULinksCheckerWordAddIn.ServiceReference.LinkTextPos))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EUCases.EULinksCheckerWordAddIn.ServiceReference.EurovocTextPos))]
    public partial class TextPos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {

        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LanguageField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LengthField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PosField;

        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Language
        {
            get
            {
                return this.LanguageField;
            }
            set
            {
                if ((object.ReferenceEquals(this.LanguageField, value) != true))
                {
                    this.LanguageField = value;
                    this.RaisePropertyChanged("Language");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Length
        {
            get
            {
                return this.LengthField;
            }
            set
            {
                if ((this.LengthField.Equals(value) != true))
                {
                    this.LengthField = value;
                    this.RaisePropertyChanged("Length");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Pos
        {
            get
            {
                return this.PosField;
            }
            set
            {
                if ((this.PosField.Equals(value) != true))
                {
                    this.PosField = value;
                    this.RaisePropertyChanged("Pos");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "ServiceReference.ILinkingService")]
    public interface ILinkingService
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ILinkingService/PutAkomaNtosoLinks", ReplyAction = "http://tempuri.org/ILinkingService/PutAkomaNtosoLinksResponse")]
        EUCases.EULinksCheckerWordAddIn.ServiceReference.AkomaNtosoXmlResult PutAkomaNtosoLinks(string akomaNtosoXml, bool removeOldLinksIfAny);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ILinkingService/UpdateLinkingStructures", ReplyAction = "http://tempuri.org/ILinkingService/UpdateLinkingStructuresResponse")]
        void UpdateLinkingStructures(string language, string json);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ILinkingService/GetLinkingStructures", ReplyAction = "http://tempuri.org/ILinkingService/GetLinkingStructuresResponse")]
        string GetLinkingStructures(string language);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ILinkingService/PutLinks", ReplyAction = "http://tempuri.org/ILinkingService/PutLinksResponse")]
        EUCases.EULinksCheckerWordAddIn.ServiceReference.TextPosWrapper PutLinks(byte[] compressedText);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ILinkingService/PutLinksText", ReplyAction = "http://tempuri.org/ILinkingService/PutLinksTextResponse")]
        EUCases.EULinksCheckerWordAddIn.ServiceReference.TextPosWrapper PutLinksText(string text);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ILinkingService/ProcessBgNatPlainTextOnlyNationals", ReplyAction = "http://tempuri.org/ILinkingService/ProcessBgNatPlainTextOnlyNationalsResponse")]
        string ProcessBgNatPlainTextOnlyNationals(string text, bool toEsacpeSpecialSymbolsInLinks);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILinkingServiceChannel : EUCases.EULinksCheckerWordAddIn.ServiceReference.ILinkingService, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LinkingServiceClient : System.ServiceModel.ClientBase<EUCases.EULinksCheckerWordAddIn.ServiceReference.ILinkingService>, EUCases.EULinksCheckerWordAddIn.ServiceReference.ILinkingService
    {

        public LinkingServiceClient()
        {
        }

        public LinkingServiceClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
        {
        }

        public LinkingServiceClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public LinkingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public LinkingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
        {
        }

        public EUCases.EULinksCheckerWordAddIn.ServiceReference.AkomaNtosoXmlResult PutAkomaNtosoLinks(string akomaNtosoXml, bool removeOldLinksIfAny)
        {
            return base.Channel.PutAkomaNtosoLinks(akomaNtosoXml, removeOldLinksIfAny);
        }

        public void UpdateLinkingStructures(string language, string json)
        {
            base.Channel.UpdateLinkingStructures(language, json);
        }

        public string GetLinkingStructures(string language)
        {
            return base.Channel.GetLinkingStructures(language);
        }

        public EUCases.EULinksCheckerWordAddIn.ServiceReference.TextPosWrapper PutLinks(byte[] compressedText)
        {
            return base.Channel.PutLinks(compressedText);
        }

        public EUCases.EULinksCheckerWordAddIn.ServiceReference.TextPosWrapper PutLinksText(string text)
        {
            return base.Channel.PutLinksText(text);
        }

        public string ProcessBgNatPlainTextOnlyNationals(string text, bool toEsacpeSpecialSymbolsInLinks)
        {
            return base.Channel.ProcessBgNatPlainTextOnlyNationals(text, toEsacpeSpecialSymbolsInLinks);
        }
    }
}
